### ISSUE TITLE
[seqbook] DNA sequence should not be displayed as nucleotide triplets

### ISSUE THREAD

**Issue by jmaupetit** [tailordev-academy/javascript-react#13]
But rather by 10-mers.

**Comment by willdurand** [comment]
yeah, makes sense! this will be an improvement to show why it is cool to have small/reusable components.

**Comment by willdurand** [comment]
so I decided not to do that for now.

**Comment by jmaupetit** [comment]
🤔 why?

**Comment by willdurand** [comment]
the way to do this is quite obscure, and it will be too long to explain. there is enough content I'd say.
