### ISSUE TITLE
JS editor line numbers are displayed over the code on FF

### ISSUE THREAD

**Issue by jmaupetit** [tailordev-academy/javascript-react#8]
## Snapshot

![screen shot 2017-09-04 at 10 21 39](https://user-images.githubusercontent.com/956157/30018383-f79e8dfa-915c-11e7-90bc-5144c6df866d.png)

**Comment by jmaupetit** [comment]
Tested with FF 57.0a1 (2017-08-31) (64-bit) (MacOSX).

**Comment by jmaupetit** [comment]
This is odd, but I have to hard-refresh every time a new JS editor widget is displayed to avoid this bug…

This time on a different laptop with FF 55.0.3 (64-bit MacOSX).

**Comment by willdurand** [comment]
Mmh let's reopen this issue then

**Comment by willdurand** [comment]
I reproduce but dont know what happens. Closing as wontfix.
